[Interface]
PrivateKey = iLeA1TVhdslrYrbNGRgvNRZLBSw+K9THLJ7xTF1KBUg=
Address = 10.10.0.2/24
ListenPort = 51820
MTU = 1420

[Peer]
PublicKey = yJsBb32IcQOZju/1IGxzmeA2AuGEGzWaOknQUobPZhs=
AllowedIPs = 10.10.0.0/24
Endpoint = 10.0.10.2:51820
PersistentKeepalive = 25